# LiteLLM Configuration

# General application settings
general_settings:
  store_prompts_in_spend_logs: true
  master_key: os.environ/LITELLM_MASTER_KEY
  salt_key: os.environ/LITELLM_SALT_KEY
  database_url: os.environ/DATABASE_URL
  store_model_in_db: true
  disable_spend_logs: true

# LiteLLM specific settings
litellm_settings:
  turn_off_message_logging: true
  global_disable_no_log_param: true

# Define common model parameters
model_defaults: &model_defaults
  model: "bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0"
  tpm: 20000
  rpm: 5
  aws_region_name: os.environ/AWS_REGION

# Model configuration
model_list:
  - model_name: "claude-3-7-load-balance"
    litellm_params:
      <<: *model_defaults
      # Default IAM role from container, using this account inference profile
      
  # Add entries for each account that can be assumed
  # IMPORTANT: Replace ACCOUNT_ID_X placeholders with your actual AWS account IDs
  # Each entry allows LiteLLM to assume a role in a different AWS account to access Bedrock
  
  - model_name: "claude-3-7-load-balance"
    litellm_params:
      <<: *model_defaults
      aws_session_name: "bedrock-ACCOUNT_ID_1"
      aws_role_name: "arn:aws:iam::ACCOUNT_ID_1:role/bedrock-caller"

  - model_name: "claude-3-7-load-balance"
    litellm_params:
      <<: *model_defaults
      aws_session_name: "bedrock-ACCOUNT_ID_2"
      aws_role_name: "arn:aws:iam::ACCOUNT_ID_2:role/bedrock-caller"

  - model_name: "claude-3-7-load-balance"
    litellm_params:
      <<: *model_defaults
      aws_session_name: "bedrock-ACCOUNT_ID_3"
      aws_role_name: "arn:aws:iam::ACCOUNT_ID_3:role/bedrock-caller"

  # Example of additional accounts - add or remove as needed
  - model_name: "claude-3-7-load-balance"
    litellm_params:
      <<: *model_defaults
      aws_session_name: "bedrock-ACCOUNT_ID_4"
      aws_role_name: "arn:aws:iam::ACCOUNT_ID_4:role/bedrock-caller"

  - model_name: "claude-3-7-load-balance"
    litellm_params:
      <<: *model_defaults
      aws_session_name: "bedrock-ACCOUNT_ID_5"
      aws_role_name: "arn:aws:iam::ACCOUNT_ID_5:role/bedrock-caller"

# Router configuration
router_settings:
  routing_strategy: "least-busy"  # Changed from simple-shuffle
  health_check_interval: 30       # Reduced from 60
  timeout: 45                     # Increased from 30
  retries: 3                      # Increased from 2
  retry_after: 5                  # Added delay between retries
