general_settings:
  store_prompts_in_spend_logs: true
  success_callback: ["prometheus"]
  failure_callback: ["prometheus"]

model_list:
  - model_name: "claude-3-7-sonnet"
    litellm_params:
      model: "bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0"
      aws_region: "us-east-1"
      tpm: 20000
      rpm: 5

  - model_name: "claude-3-5-sonnet"
    litellm_params:
      model: "bedrock/us.anthropic.claude-3-5-sonnet-20240620-v1:0"
      aws_region: "us-east-1"
      tpm: 20000
      rpm: 5

  - model_name: "gpt-4o"
    litellm_params:
      model: "openai/gpt-4o"
      api_key: "${OPENAI_API_KEY}"
      tpm: 20000
      rpm: 5

router_settings:
  routing_strategy: "least-busy"  
  health_check_interval: 30       
  timeout: 45                     
  retries: 5                      
  retry_after: 10
